apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sf-linkmobility
  namespace: hot-crm
  labels:
    team: hot-crm
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: /internal/is_alive
  readiness:
    path: /internal/is_ready
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 10m
      memory: 256Mi
  envFrom:
    - secret: sf-linkmobility
  ingresses:
    - "https://linkmobility.ekstern.dev.nav.no"
    - "https://linkmobility.intern.dev.nav.no"
  accessPolicy:
    outbound:
      external:
        - host: test.salesforce.com
        - host: navdialog--sit2.my.salesforce.com
  env:
    - name: SF_TOKENHOST
      value: 'https://test.salesforce.com/services/oauth2/token'
    - name: SF_VERSION
      value: 'v57.0'