apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sf-linkmobility
  namespace: teamcrm
  labels:
    team: teamcrm
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 2
    max: 3
  liveness:
    path: /internal/is_alive
  readiness:
    path: /internal/is_ready
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 10m
      memory: 256Mi
  envFrom:
    - secret: sf-linkmobility
#  ingresses:
#    - "https://linkmobility.nav.no"
  accessPolicy:
    outbound:
      external:
        - host: login.salesforce.com
        - host: navdialog.my.salesforce.com
  env:
    - name: SF_TOKENHOST
      value: 'https://login.salesforce.com/services/oauth2/token'
    - name: SF_VERSION
      value: 'v57.0'