apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sf-linkmobility
  namespace: teamcrm
  labels:
    team: teamcrm
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: /internal/is_alive
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 512Mi
  prometheus:
    enabled: true
    path: /internal/prometheus
  ingresses:
    - "https://linkmobility.nav.no"
  accessPolicy:
    outbound:
      external:
        - host: login.salesforce.com
        - host: navdialog.my.salesforce.com
  envFrom:
    - secret: sf-linkmobility
  env:
    - name: KTOR_ENV
      value: production
    - name: MS_BETWEEN_WORK
      value: '600000'
    - name: VAULT_INSTANCE
      value: GCP
    - name: SF_INSTANCE
      value: PRODUCTION
    - name: SF_TOKENHOST
      value: 'https://login.salesforce.com'
    - name: SF_VERSION
      value: 'v48.0'